ios/fastlane/Fastfile

Update fastfile for Transporter behind firewall

---

ios/Podfile

Use incremental installation for faster iOS builds

---

.github/workflows/build_android.yml
.github/workflows/build_ios.yml
ios/fastlane/Matchfile
screenshots_android.yaml
screenshots_ios.yaml

Sreenshots for cd

---

.gitignore
ios/Runner/AppDelegate.swift
lib/app/app.dart
lib/app/main.dart
lib/app/main_rdt.dart
lib/middleware/middleware.dart
lib/models/actions/print_fcm_token.dart
lib/models/actions/request_fcm_permissions.dart
lib/services/notifications_service.dart
test_driver/app.dart
test_driver/app_test.dart
test_driver/mocks/notifications_service_mocks.dart

- added a notifications service and a mock for integration tests
- moved FirebaseMessaging setup to service
- added actions and middleware for notifications
- fixed AppDelegate, removed duplicate functionality
fixes #23

Add notifications service

---

.github/workflows/build_and_deploy.yml
.gitignore

Use altool instead of fastlane (transporter)

---

lib/actions/conversations/disregard_messages.dart
lib/actions/conversations/observe_messages.dart
lib/actions/conversations/save_message.dart
lib/actions/conversations/store_messages.dart
lib/actions/conversations/update_conversation_page.dart
lib/middleware/conversations_middleware.dart
lib/models/app/app_state.dart
lib/models/app/serializers.dart
lib/models/conversations/conversation/message.dart
lib/models/conversations/conversation/vm_conversation_page.dart
lib/models/enums/problem_type.dart
lib/reducers/conversations_reducers.dart
lib/services/conversations_service.dart
lib/widgets/conversations/conversation/conversation_page.dart
lib/widgets/conversations/conversation/message_entry.dart
lib/widgets/conversations/conversation/message_tile.dart
lib/widgets/conversations/conversation/messages_list.dart
test/unit/models/app_state_test.dart

Allow sending messages

---

README.md
lib/actions/profile/select_profile_pic.dart
lib/actions/profile/update_profile_page.dart
lib/enums/problem_type.dart
lib/extensions/firestore_extensions.dart
lib/middleware/profile_middleware.dart
lib/models/app/app_state.dart
lib/models/app/serializers.dart
lib/models/profile/vm_profile_page.dart
lib/reducers/profile_reducers.dart
lib/services/database_service.dart
lib/widgets/profile/list_profile_avatar.dart
lib/widgets/profile/profile_avatar.dart
lib/widgets/profile/profile_page.dart
lib/widgets/profile/profile_pics_list.dart
lib/widgets/profile/uploading_profile_avatar.dart

fixes #97 
- new action: SelectProfilePic
- updated action: UpdateProfilePage (removed leaguer, added
userId, leaguerPhotoURL, selectingProfilePic)
- new middleware: _updateLeaguer (saves selected profilePic to db)
- updated models: VmProfilePage (same as UpdateProfilePage action)
- updated reducer: _updateProfilePage (same as UpdateProfilePage action)
- updated services: added DatabaseService.updateLeaguer
- new widgets: ListProfileAvatar, ProfilePicsList,
UploadingProfileAvatar
- updated widgets: ProfileAvatar (removed filePath option), ProfilePage
(added listview for selecting a profile pic)

Add profile pic selection

---

.github/workflows/ci_cd.yml

Remove unnecessary CI runs

---

lib/reducers/profile_reducers.dart
test/mocks/profile_pic_mocks.dart
test/unit/reducers/profile_reducers_test.dart

i128 Selecting a profile pic can get stuck

---

analysis_options.yaml
functions/package-lock.json
functions/package.json
ios/Podfile
ios/Podfile.lock
lib/main_local_rdt.dart
lib/main_rdt.dart
pubspec.lock

- ran flutter pub upgrade
- ran npm update in functions/
- removed Podfile triggering update

Update dart deps, functions/ and Podfile

---

.github/workflows/ci_cd.yml

Fixes #152
- change CI workflow file to use release branch

Change master branch to release

---

lib/widgets/auth/auth_page.dart
test/widget/auth_widget_test.dart

Layout of Auth Page on smaller phones is wack

---

test/mocks/verify_dispatch_middleware.dart

Make a middleware for testing action dispatch

---

test/mocks/verify_dispatch_middleware.dart

i197: VerifyDispatchMiddleware clears actions list

---

lib/widgets/auth/other_auth_options_page.dart

Other Auth Options Page overflows on smaller screens

---

ios/Podfile.lock

- part of fixing a build error

Run pod update

---

lib/models/app/app_state.dart
lib/models/app/system_info.dart
lib/reducers/auth/clear_user_data.dart
lib/reducers/auth/update_other_auth_options_page.dart
lib/reducers/device/store_platform.dart
lib/utils/serializers.dart
lib/widgets/auth/auth_page.dart
test/unit/middleware/check_platform_middleware_test.dart
test/unit/reducers/store_platform_reducer_test.dart
test/widget/auth_page_widget_test.dart

Fixes #206
- added a new model object for systemInfo
- chaned ClearUserData reducer to not wipe the systemInfo

Google Sign In shows on iOS

---

lib/widgets/auth/other_auth_options_page.dart

minus a couple UX points, but still fixes #205

i205: overlayed keyboard as fix

---

lib/widgets/auth/other_auth_options_page.dart
test/widget/auth/auth_page_widget_test.dart
test/widget/auth/other_auth_options_page_widget_test.dart

i210 : use device service to get platform type in otherAuthOptionsPage

---

lib/widgets/auth/other_auth_options_page.dart
test/widget/auth/other_auth_options_page_widget_test.dart

i217: clear textFormFields in redux store when change from email sign in to sign up 

---

test_driver/no_driver.dart

Add a "no_driver" integration test

---

lib/widgets/auth/email_auth_options_page.dart
pubspec.lock

Fixes #227
Seems to be all good - tests all pass and manual testing shows validators working as expected

i227: Refactor form validators to turnery operators

---

ios/Runner.xcodeproj/project.pbxproj

i239: Fix Sign In With Apple not working

---

lib/widgets/auth/email_auth_options_page.dart

i214: make emailAuthOptionsScreen scrollable

---

lib/middleware/auth/sign_in_with_email.dart
lib/middleware/auth/sign_out_user.dart
lib/middleware/auth/sign_up_with_email.dart
lib/services/auth_service.dart
pubspec.lock
test/mocks/auth/apple_signin_mocks.dart
test/mocks/auth/firebase_auth_mocks.dart
test/mocks/auth/google_signin_mocks.dart
test/mocks/mock_firebase_platform.dart
test/unit/middleware/auth/sign_in_with_email_middleware_test.dart
test/unit/middleware/auth/sign_up_with_email_middleware_test.dart
test/unit/services/auth_service_test.dart

i228: tested authService

---

lib/middleware/app_middleware.dart
lib/middleware/profile/delete_profile_pic.dart
lib/widgets/profile/list_profile_avatar.dart

i159: Add a confirmation dialog when user deletes a ProfilePic

---

lib/reducers/profile/store_profile_pics.dart
lib/services/auth_service.dart
lib/services/notifications_service.dart
test/mocks/navigation/global_key_mocks.dart
test/mocks/services/auth_service_mocks.dart
test/mocks/services/database_service_mocks.dart
test/unit/middleware/auth/sign_in_with_email_middleware_test.dart
test/unit/reducers/reducers_test.dart
test/unit/services/auth_service_test.dart
test/utils/services_bundle_mocks.dart
test_driver/firebase_emulators_test.dart
test_driver/mocks/storage_service_mocks.dart
test_driver/screenshots_app_test.dart

i145: Get rid of all TODOs

---

analysis_options.yaml

i33: Use stricter static analysis to enforce style guide

---

test/unit/reducers/clear_user_data_test.dart

Thought of an improvement to my lazy way of testing so putting up a PR with an example of how we might test without extra layers involved (ie. the store)

Change reducer test to test on the metal

---

android/build.gradle
lib/widgets/main/nav_bar.dart
test/widget/crowd_league_app/crowd_league_app_test.dart

i160: Add widget tests for navigation

---

test/unit/middleware/auth/sign_up_with_email_middleware_test.dart

review additives for i223 pr

---

test/mocks/redux/redux_store_mocks.dart
test/utils/widget_test_harness.dart
test/widget/auth/auth_page_test.dart

Fixes #232
Just made the harness and updated one test, will add an Asana task to update all widget tests if we're happy with the harness.

Simplify widget test setup with WidgetTestHarness

---

.vscode/redux.code-snippets

Fixes #134
- one less character to type for snippets 
- discussed change with team in standup, got the go ahead

Update snippets from blt_x to bv_x

---

.vscode/redux.code-snippets

Update middleware snippets

---

.contributing/code-of-conduct.md
.contributing/style-guide.md

This means any changes must be done by PR which gives everyone the chance to have input
- the new docs are just copied straight from the current wiki pages 
- after the new docs are merged we should delete the wiki pages 
- the normal process should apply for changes to the contributing docs, except all team members should always be requested for review

Move: contributing docs out of wiki into main repo

---

.vscode/redux.code-snippets

Add as many imports as possible to middleware and reducer snippets

---

.vscode/redux.code-snippets

- used workspace name over hard coded value
- also used upper case S for service

Fix: small fixes for snippets

---

.contributing/code-of-conduct.md

This was an attempt to capture what we spoke about today.  The purpose is to be a starting point for discussion rather than as a suggestion of what I think the end product should look like.  
There is no rush on this, please feel free to take the time to think about it if you would like to.  
Thanks!

Add items: clean workspaces and clear descriptions

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
pubspec.lock

- updated to AS 4.1.1 and accepted suggested updates to project

Update: accept updates from Android Studio 4.1.1

---

.contributing/the-process.md

For now, just moved the contents of [The Process < Planning (CL) - Google Docs](https://docs.google.com/document/d/1sMq82Zwt120PHdsOPq5NA2BpuyezvQuq-2O0Dakixdo/edit) to .contributing/the-process.md

Add The Process doc to the repo so changes require PRs

---

.github/workflows/ci_cd.yml
lib/models/problems/problem_base.dart
lib/utils/problem_utils.dart
lib/widgets/conversations/conversation_summaries_page/conversation_summary_tile.dart
pubspec.lock
test/unit/extensions/stream_controller_extensions_test.dart
test/unit/reducers/reducers_test.dart

There isn't an issue associated with this one.
Have a look, let me know what you think

Refactor problem_utils and Problem creation

---

.contributing/code-of-conduct.md

Following up from our RTC today, this is my attempt at capturing what we agreed on.

Add a Reviews section to Code of Conduct

---

.contributing/the-process.md

Added a step to look for design inspiration in Dribbble and/or Uplabs.  This came out of realising how much easier I found coming up with a design after seeing some cool options.

Update The Process: add to "Do a design review" step

---

.contributing/the-process.md

changed "-" to "<" on 1 line - made naming files/folders more consistent across process doc

Formatting update to process doc

---

.contributing/the-process.md

created from comment in last pr:
'It took me a little while to remember that we had the key down the bottom - could we refer to it here? maybe with a eg. [1] and then have the items in the key numbered?'

suggestion: clearer key in process doc

---

.contributing/the-process.md

based on my findings from creating input sessions this week, hopefully it deepens the flow of the process (doc)!

process doc imporvement:  input sessions flow

---

.contributing/the-process.md

Changed step 5 of User Flow to use a Google Presentation

Update The Process to use a Google Presentation
